[package]
name = "qubit-rust"
version = "0.1.0"
authors = ["cfr2ak <cfr2ak@gmail.com>"]
edition = "2020"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7"

